/*************************************************************************
*
* FIBO Library - Version 1.0 - September 1st, 2020
* @author thuyetvp@gmail.com
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*/

#pragma once
#pragma warning(disable : 4127)

#if DBG

//
//  Debugging level flags.
//

#define KEDBG_TRACE_ROUTINES            0x00000001
#define KEDBG_TRACE_OPERATION_STATUS    0x00000002
#define KEDBG_TRACE_DEBUG               0x00000004
#define KEDBG_TRACE_ERROR               0x00000008
constexpr ULONG KEDBG_TRACE_FLAGS = KEDBG_TRACE_ROUTINES | KEDBG_TRACE_OPERATION_STATUS | KEDBG_TRACE_DEBUG | KEDBG_TRACE_ERROR;

#define KE_DBG_PRINT( _dbgLevel, _string )          \
    if(FlagOn(KEDBG_TRACE_FLAGS,(_dbgLevel))) {    \
        DbgPrint _string;                           \
    }

#else

#define KE_DBG_PRINT(_dbgLevel, _string)            {NOTHING;}

#endif

#define LOGENTER            KE_DBG_PRINT(KEDBG_TRACE_ROUTINES, (DRIVER_PREFIX __FUNCTION__ " enter {\n"))
#define LOGEXIT             KE_DBG_PRINT(KEDBG_TRACE_ROUTINES, (DRIVER_PREFIX __FUNCTION__ " exit }\n"))
#define ERROR_PREFIX        "[error] "